/**
 * A curated map of common English misspellings to their correction. These are
 * applied with high confidence (still respecting user rejections and unsafe
 * fields) so the most frequent typos always get fixed, regardless of what the
 * frequency list or validator contains. Every key is a non-word, so it never
 * collides with correctly-spelled input.
 */
export interface HardCorrections {
  correctionFor(word: string): string | null;
}

export function createHardCorrections(
  map: Readonly<Record<string, string>>,
): HardCorrections {
  const lower = new Map<string, string>();
  for (const [misspelling, correction] of Object.entries(map)) {
    lower.set(misspelling.toLowerCase(), correction);
  }
  return {
    correctionFor: (word) => lower.get(word.toLowerCase()) ?? null,
  };
}

const COMMON_MISSPELLINGS: Record<string, string> = {
  teh: "the",
  adn: "and",
  hte: "the",
  thsi: "this",
  taht: "that",
  alot: "a lot",
  abt: "about",
  recieve: "receive",
  recieved: "received",
  recieving: "receiving",
  beleive: "believe",
  beleived: "believed",
  seperate: "separate",
  seperated: "separated",
  seperately: "separately",
  definately: "definitely",
  defiantly: "definitely",
  occured: "occurred",
  occuring: "occurring",
  occurence: "occurrence",
  untill: "until",
  wich: "which",
  thier: "their",
  becuase: "because",
  becasue: "because",
  alway: "always",
  allways: "always",
  wierd: "weird",
  freind: "friend",
  freinds: "friends",
  goverment: "government",
  enviroment: "environment",
  neccessary: "necessary",
  necesary: "necessary",
  accross: "across",
  agressive: "aggressive",
  apparant: "apparent",
  arguement: "argument",
  calender: "calendar",
  cemetary: "cemetery",
  collegue: "colleague",
  comming: "coming",
  commited: "committed",
  completly: "completely",
  concious: "conscious",
  embarass: "embarrass",
  enviornment: "environment",
  existance: "existence",
  experiance: "experience",
  familar: "familiar",
  finaly: "finally",
  foriegn: "foreign",
  fourty: "forty",
  gaurd: "guard",
  grammer: "grammar",
  happend: "happened",
  immediatly: "immediately",
  independant: "independent",
  knowlege: "knowledge",
  liason: "liaison",
  libary: "library",
  maintainance: "maintenance",
  mispell: "misspell",
  noticable: "noticeable",
  occassion: "occasion",
  persistant: "persistent",
  posession: "possession",
  prefered: "preferred",
  privelege: "privilege",
  probaly: "probably",
  publically: "publicly",
  reccomend: "recommend",
  refered: "referred",
  relevent: "relevant",
  rythm: "rhythm",
  succesful: "successful",
  supercede: "supersede",
  suprise: "surprise",
  tommorow: "tomorrow",
  truely: "truly",
  unfortunatly: "unfortunately",
  usefull: "useful",
  wether: "whether",
  nite: "night",
  // Additional well-established misspellings and common inflections. Every key is
  // a non-word; even if one were a real word, the originalIsValid guard in
  // decideCorrection means it would simply never fire.
  accomodate: "accommodate",
  accomodation: "accommodation",
  acheive: "achieve",
  acheived: "achieved",
  acheivement: "achievement",
  adress: "address",
  basicly: "basically",
  begining: "beginning",
  buisness: "business",
  catagory: "category",
  cheif: "chief",
  decison: "decision",
  desicion: "decision",
  dissapoint: "disappoint",
  dissapointed: "disappointed",
  dissappear: "disappear",
  embarassing: "embarrassing",
  embarassment: "embarrassment",
  enviromental: "environmental",
  equiptment: "equipment",
  febuary: "february",
  foward: "forward",
  fullfill: "fulfill",
  garantee: "guarantee",
  guarentee: "guarantee",
  harrass: "harass",
  harrassment: "harassment",
  heirarchy: "hierarchy",
  imediately: "immediately",
  interupt: "interrupt",
  intresting: "interesting",
  irresistable: "irresistible",
  millenium: "millennium",
  minature: "miniature",
  mischievious: "mischievous",
  neice: "niece",
  occasionaly: "occasionally",
  occassionally: "occasionally",
  paralel: "parallel",
  parralel: "parallel",
  peice: "piece",
  percieve: "perceive",
  perseverence: "perseverance",
  personell: "personnel",
  possesion: "possession",
  priviledge: "privilege",
  pronounciation: "pronunciation",
  realy: "really",
  recomend: "recommend",
  rediculous: "ridiculous",
  religous: "religious",
  remeber: "remember",
  repitition: "repetition",
  restarant: "restaurant",
  resturant: "restaurant",
  sacrafice: "sacrifice",
  safty: "safety",
  secratary: "secretary",
  seige: "siege",
  sieze: "seize",
  similiar: "similar",
  sincerly: "sincerely",
  speach: "speech",
  sucessful: "successful",
  succesfully: "successfully",
  surprize: "surprise",
  temparature: "temperature",
  tendancy: "tendency",
  threshhold: "threshold",
  tommorrow: "tomorrow",
  twelth: "twelfth",
  vaccum: "vacuum",
  vaccuum: "vacuum",
  vehical: "vehicle",
  wonderfull: "wonderful",
  writen: "written",
  writting: "writing",
};

export function createCommonHardCorrections(): HardCorrections {
  return createHardCorrections(COMMON_MISSPELLINGS);
}
